// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace DashBoardExample
{
	
	
	public partial class Resource
	{
		
		public partial class Attribute
		{
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040002
			public const int background = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int foreground1 = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int title_background = 2130968576;
			
			// aapt resource value: 0x7f040003
			public const int white = 2130968579;
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f050003
			public const int text_size_large = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int text_size_medium = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int text_size_small = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int title_height = 2131034112;
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int android__logo_froyo = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int android_eclair_logo = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int android_gingerbread_logo = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int android_honeycomb_logo = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int android_ics_logo = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int android_jellybean_logo = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ic_feedback = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int ic_home = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int ic_launcher = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int Icon = 2130837513;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080007
			public const int btnFeedback = 2131230727;
			
			// aapt resource value: 0x7f080004
			public const int btnHome = 2131230724;
			
			// aapt resource value: 0x7f080001
			public const int header = 2131230721;
			
			// aapt resource value: 0x7f080008
			public const int main_btn_eclair = 2131230728;
			
			// aapt resource value: 0x7f080009
			public const int main_btn_froyo = 2131230729;
			
			// aapt resource value: 0x7f08000a
			public const int main_btn_gingerbread = 2131230730;
			
			// aapt resource value: 0x7f08000b
			public const int main_btn_honeycomb = 2131230731;
			
			// aapt resource value: 0x7f08000c
			public const int main_btn_ics = 2131230732;
			
			// aapt resource value: 0x7f08000d
			public const int main_btn_jellybean = 2131230733;
			
			// aapt resource value: 0x7f080003
			public const int panelIconLeft = 2131230723;
			
			// aapt resource value: 0x7f080006
			public const int panelIconRight = 2131230726;
			
			// aapt resource value: 0x7f080002
			public const int textView1 = 2131230722;
			
			// aapt resource value: 0x7f080005
			public const int txtHeading = 2131230725;
			
			// aapt resource value: 0x7f080000
			public const int vsHeader = 2131230720;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int activity_eclair = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int activity_feedback = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int activity_froyo = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int activity_gingerbread = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int activity_honeycomb = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int activity_ics = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int activity_jellybean = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int header = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int Main = 2130903048;
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060005
			public const int EclairActivityTitle = 2131099653;
			
			// aapt resource value: 0x7f060004
			public const int FeedbackActivityTitle = 2131099652;
			
			// aapt resource value: 0x7f060006
			public const int FroyoActivityTitle = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int GingerbreadActivityTitle = 2131099655;
			
			// aapt resource value: 0x7f060003
			public const int HomeActivityTitle = 2131099651;
			
			// aapt resource value: 0x7f060008
			public const int HoneycombActivityTitle = 2131099656;
			
			// aapt resource value: 0x7f060009
			public const int ICSActivityTitle = 2131099657;
			
			// aapt resource value: 0x7f06000a
			public const int JellyBeanActivityTitle = 2131099658;
			
			// aapt resource value: 0x7f060001
			public const int app_name = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int hello = 2131099648;
			
			// aapt resource value: 0x7f060002
			public const int txtDemo = 2131099650;
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070001
			public const int HomeButton = 2131165185;
			
			// aapt resource value: 0x7f070000
			public const int heading_text = 2131165184;
			
			private Style()
			{
			}
		}
	}
}
