// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace SplashScreen
{
	
	
	public partial class Resource
	{
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int alpha = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int translate = 2130968577;
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int radialback = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int splash3 = 2130837506;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060000
			public const int button1 = 2131099648;
			
			// aapt resource value: 0x7f060002
			public const int imgMain = 2131099650;
			
			// aapt resource value: 0x7f060001
			public const int lnMain = 2131099649;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Splash = 2130903041;
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int app_name = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int hello = 2131034112;
			
			private String()
			{
			}
		}
	}
}
